files:
  - source: /DIY_LoopApp/CGMBLEKit/en.xcloc/Localized Contents/en.xliff
    translation: >-
      /DIY_LoopApp/CGMBLEKit/%osx_
      Contents/%osx_locale%.xliff
  - source: /DIY_LoopApp/G4ShareSpy/en.xcloc/Localized Contents/en.xliff
    translation: >-
      /DIY_LoopApp/G4ShareSpy/%osx
      Contents/%osx_locale%.xliff
  - source: /DIY_LoopApp/Loop/en.xcloc/Localized Contents/en.xliff
    translation: /DIY_LoopApp/Loop/%osx_locale%.xcloc/Localized Contents/%osx_locale%.xliff
  - source: /DIY_LoopApp/LoopKit/en.xcloc/Localized Contents/en.xliff
    translation: >-
      /DIY_LoopApp/LoopKit/%osx_lo
      Contents/%osx_locale%.xliff
  - source: /DIY_LoopApp/NightscoutService/en.xcloc/Localized Contents/en.xliff
    translation: >-
      /DIY_LoopApp/NightscoutServi
      Contents/%osx_locale%.xliff
  - source: /DIY_LoopApp/RileyLink/en.xcloc/Localized Contents/en.xliff
    translation: >-
      /DIY_LoopApp/RileyLink/%osx_
      Contents/%osx_locale%.xliff
  - source: /DIY_LoopApp/ShareClient/en.xcloc/Localized Contents/en.xliff
    translation: >-
      /DIY_LoopApp/ShareClient/%os
      Contents/%osx_locale%.xliff
